/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <thrift/TProtocol.h>
#import <thrift/TApplicationException.h>
#import <thrift/TProtocolException.h>
#import <thrift/TProtocolUtil.h>
#import <thrift/TProcessor.h>
#import <thrift/TObjective-C.h>
#import <thrift/TBase.h>
#import <thrift/TAsyncTransport.h>
#import <thrift/TProtocolFactory.h>
#import <thrift/TBaseClient.h>

#import "shared.h"

//typedef AuthenticationToken * AuthenticationToken;

@interface CompanyAuthenticationResult : NSObject <TBase, NSCoding> {
    BOOL __success;
    NSString * __message;
    AuthenticationToken *__authenticationToken;
    NSString * __companyId;
    NSString * __appName;
    
    BOOL __success_isset;
    BOOL __message_isset;
    BOOL __authenticationToken_isset;
    BOOL __companyId_isset;
    BOOL __appName_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=success, setter=setSuccess:) BOOL success;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, retain, getter=authenticationToken, setter=setAuthenticationToken:) AuthenticationToken* authenticationToken;
@property (nonatomic, retain, getter=companyId, setter=setCompanyId:) NSString * companyId;
@property (nonatomic, retain, getter=appName, setter=setAppName:) NSString * appName;
#endif

- (id) init;
- (id) initWithSuccess: (BOOL) success message: (NSString *) message authenticationToken: (AuthenticationToken*) authenticationToken companyId: (NSString *) companyId appName: (NSString *) appName;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (BOOL) success;
- (void) setSuccess: (BOOL) success;
#endif
- (BOOL) successIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

#if !__has_feature(objc_arc)
- (AuthenticationToken) authenticationToken;
- (void) setAuthenticationToken: (AuthenticationToken) authenticationToken;
#endif
- (BOOL) authenticationTokenIsSet;

#if !__has_feature(objc_arc)
- (NSString *) companyId;
- (void) setCompanyId: (NSString *) companyId;
#endif
- (BOOL) companyIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) appName;
- (void) setAppName: (NSString *) appName;
#endif
- (BOOL) appNameIsSet;

@end

@interface UserAuthenticationResult : NSObject <TBase, NSCoding> {
    BOOL __success;
    NSString * __message;
    AuthenticationToken *__authenticationToken;
    NSString * __userPrincipal;
    NSString * __appName;
    
    BOOL __success_isset;
    BOOL __message_isset;
    BOOL __authenticationToken_isset;
    BOOL __userPrincipal_isset;
    BOOL __appName_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=success, setter=setSuccess:) BOOL success;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, retain, getter=authenticationToken, setter=setAuthenticationToken:) AuthenticationToken* authenticationToken;
@property (nonatomic, retain, getter=userPrincipal, setter=setUserPrincipal:) NSString * userPrincipal;
@property (nonatomic, retain, getter=appName, setter=setAppName:) NSString * appName;
#endif

- (id) init;
- (id) initWithSuccess: (BOOL) success message: (NSString *) message authenticationToken: (AuthenticationToken*) authenticationToken userPrincipal: (NSString *) userPrincipal appName: (NSString *) appName;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (BOOL) success;
- (void) setSuccess: (BOOL) success;
#endif
- (BOOL) successIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

#if !__has_feature(objc_arc)
- (AuthenticationToken) authenticationToken;
- (void) setAuthenticationToken: (AuthenticationToken) authenticationToken;
#endif
- (BOOL) authenticationTokenIsSet;

#if !__has_feature(objc_arc)
- (NSString *) userPrincipal;
- (void) setUserPrincipal: (NSString *) userPrincipal;
#endif
- (BOOL) userPrincipalIsSet;

#if !__has_feature(objc_arc)
- (NSString *) appName;
- (void) setAppName: (NSString *) appName;
#endif
- (BOOL) appNameIsSet;

@end

@interface DeviceAuthenticationResult : NSObject <TBase, NSCoding> {
    BOOL __success;
    NSString * __message;
    AuthenticationToken *__authenticationToken;
    NSString * __deviceId;
    NSString * __appName;
    
    BOOL __success_isset;
    BOOL __message_isset;
    BOOL __authenticationToken_isset;
    BOOL __deviceId_isset;
    BOOL __appName_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=success, setter=setSuccess:) BOOL success;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, retain, getter=authenticationToken, setter=setAuthenticationToken:) AuthenticationToken* authenticationToken;
@property (nonatomic, retain, getter=deviceId, setter=setDeviceId:) NSString * deviceId;
@property (nonatomic, retain, getter=appName, setter=setAppName:) NSString * appName;
#endif

- (id) init;
- (id) initWithSuccess: (BOOL) success message: (NSString *) message authenticationToken: (AuthenticationToken*) authenticationToken deviceId: (NSString *) deviceId appName: (NSString *) appName;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (BOOL) success;
- (void) setSuccess: (BOOL) success;
#endif
- (BOOL) successIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

#if !__has_feature(objc_arc)
- (AuthenticationToken) authenticationToken;
- (void) setAuthenticationToken: (AuthenticationToken) authenticationToken;
#endif
- (BOOL) authenticationTokenIsSet;

#if !__has_feature(objc_arc)
- (NSString *) deviceId;
- (void) setDeviceId: (NSString *) deviceId;
#endif
- (BOOL) deviceIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) appName;
- (void) setAppName: (NSString *) appName;
#endif
- (BOOL) appNameIsSet;

@end

@interface SettingsAuthenticationResult : NSObject <TBase, NSCoding> {
    NSString * __settingKey;
    NSString * __appName;
    NSString * __settingVal;
    NSString * __settingId;
    
    BOOL __settingKey_isset;
    BOOL __appName_isset;
    BOOL __settingVal_isset;
    BOOL __settingId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=settingKey, setter=setSettingKey:) NSString * settingKey;
@property (nonatomic, retain, getter=appName, setter=setAppName:) NSString * appName;
@property (nonatomic, retain, getter=settingVal, setter=setSettingVal:) NSString * settingVal;
@property (nonatomic, retain, getter=settingId, setter=setSettingId:) NSString * settingId;
#endif

- (id) init;
- (id) initWithSettingKey: (NSString *) settingKey appName: (NSString *) appName settingVal: (NSString *) settingVal settingId: (NSString *) settingId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) settingKey;
- (void) setSettingKey: (NSString *) settingKey;
#endif
- (BOOL) settingKeyIsSet;

#if !__has_feature(objc_arc)
- (NSString *) appName;
- (void) setAppName: (NSString *) appName;
#endif
- (BOOL) appNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) settingVal;
- (void) setSettingVal: (NSString *) settingVal;
#endif
- (BOOL) settingValIsSet;

#if !__has_feature(objc_arc)
- (NSString *) settingId;
- (void) setSettingId: (NSString *) settingId;
#endif
- (BOOL) settingIdIsSet;

@end

@protocol AuthenticationService <NSObject>
- (SettingsAuthenticationResult *) authenticateSetting: (NSString *) appName;  // throws TException
- (CompanyAuthenticationResult *) authenticateCompany: (NSString *) companyId companySecret: (NSString *) companySecret appName: (NSString *) appName;  // throws TException
- (UserAuthenticationResult *) authenticateUser: (AuthenticationToken*) companyAuthenticationToken userPrincipal: (NSString *) userPrincipal userCredentials: (NSString *) userCredentials appName: (NSString *) appName;  // throws TException
- (DeviceAuthenticationResult *) authenticateDevice: (AuthenticationToken*) UserAuthenticationToken deviceId: (NSString *) deviceId appName: (NSString *) appName;  // throws TException
- (void) deauthenticate: (AuthenticationToken*) token;  // throws TException
@end

@interface AuthenticationServiceClient : TBaseClient <AuthenticationService> - (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface AuthenticationServiceProcessor : NSObject <TProcessor> {
    id <AuthenticationService> mService;
    NSDictionary * mMethodMap;
}
- (id) initWithAuthenticationService: (id <AuthenticationService>) service;
- (id<AuthenticationService>) service;
@end

@interface authcConstants : NSObject {
}
@end
