/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <thrift/TProtocol.h>
#import <thrift/TApplicationException.h>
#import <thrift/TProtocolException.h>
#import <thrift/TProtocolUtil.h>
#import <thrift/TProcessor.h>
#import <thrift/TObjective-C.h>
#import <thrift/TBase.h>
#import <thrift/TAsyncTransport.h>
#import <thrift/TProtocolFactory.h>
#import <thrift/TBaseClient.h>

#import "shared.h"

//typedef AuthenticationToken * AuthenticationToken;

//typedef Profile * Profile;

@protocol ProvisioningService <NSObject>
- (Profile*) checkProvision: (AuthenticationToken*) token applicationId: (NSString *) applicationId localProfile: (Profile*) localProfile;  // throws TException
@end

@interface ProvisioningServiceClient : TBaseClient <ProvisioningService> - (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ProvisioningServiceProcessor : NSObject <TProcessor> {
    id <ProvisioningService> mService;
    NSDictionary * mMethodMap;
}
- (id) initWithProvisioningService: (id <ProvisioningService>) service;
- (id<ProvisioningService>) service;
@end

@interface provisionConstants : NSObject {
}
@end
