[supervisord]
logfile=/dev/null
pidfile=/var/run/supervisord.pid
nodaemon=true

[program:livo-server]
command=/usr/bin/java -Duser.language=en -Duser.country=US -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=6667 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dfelix.fileinstall.dir=/var/opt/livod/conf/services -Dlivo.home=/var/opt/livod/ -jar bin/felix.jar 
environment=PATH=/usr/lib/jvm/java-7-openjdk-amd64/bin/
directory=/srv/livod/
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
auto_start=true
priority=0

[program:livo-web-ui]
command=/usr/share/tomcat8/bin/catalina.sh run -Djava.awt.headless=true -Xmx128M
environment=JAVA_HOME="/usr/lib/jvm/java-7-openjdk-amd64/",CATALINA_HOME="/usr/share/tomcat8",CATALINA_BASE="/var/lib/tomcat8",CATALINA_PID="/var/run/tomcat8.pid",CATALINA_TMPDIR="/tmp/web-ui/"
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
auto_start=true
autorestart=true
